Password script fixes

diff --git a/templates/shared_services/sonatype-nexus/terraform/cloud-config.yaml b/templates/shared_services/sonatype-nexus/terraform/cloud-config.yaml
--- a/templates/shared_services/sonatype-nexus/terraform/cloud-config.yaml
+++ b/templates/shared_services/sonatype-nexus/terraform/cloud-config.yaml
@@ -48,20 +48,78 @@ write_files:
         docker system prune -f
       fi
     permissions: '0755'
-  # configure Nexus to disable default repos and set up SSL
+
+  # Configure Nexus to disable default repos
   - path: /etc/nexus-data/etc/nexus.properties
     content: |
       nexus.skipDefaultRepositories=true
+    permissions: '0755'
+
+  # Set up Nexus to serve https using SSL cert
+  - path: /home/adminuser/configure-nexus-ssl.sh
+    content: |
+      # Prepare ssl certificate
+      az login --identity -u ${msi_id}
+      # -- get cert from kv as secret so it contains private key
+      echo 'Getting cert and cert password from Keyvault...'
+      az keyvault secret download --vault-name ${vault_name} --name ${ssl_cert_name} --file temp.pfx --encoding base64
+      CERT_PASSWORD=$(az keyvault secret show --vault-name ${vault_name} --name ${ssl_cert_password_name} -o tsv --query value)
+      # -- az cli strips out password from cert which we need to re-add for jks by converting to PEM then back to PFX with pwd
+      openssl pkcs12 -in temp.pfx -out temp.pem -nodes -password pass:
+      openssl pkcs12 -export -out nexus-ssl.pfx -in temp.pem -password "pass:$CERT_PASSWORD"
+
+      # Import ssl cert to keystore within Nexus volume
+      keystore_timeout=300
+      echo 'Checking for nexus-data/keystores directory...'
+      while [ ! -d /etc/nexus-data/keystores ]; do
+        # Wait for /keystore dir to be created by container first
+        if [ $keystore_timeout == 0 ]; then
+          echo 'ERROR - Timeout while waiting for Nexus to create nexus-data/keystores'
+          exit 1
+        fi
+        sleep 1
+        ((keystore_timeout--))
+      done
+      echo 'Directory found. Importing ssl cert into new keystore at nexus-data/keystores/keystore.jks...'
+      keytool -v -importkeystore -srckeystore nexus-ssl.pfx -srcstoretype PKCS12 -destkeystore /etc/nexus-data/keystores/keystore.jks \
+        -deststoretype JKS -srcstorepass "$CERT_PASSWORD" -deststorepass "$CERT_PASSWORD"
+
+      # Configure Jetty instance within Nexus to consume ssl cert
+      echo 'Modifying Nexus Jetty configuration to enable ssl...'
+      mkdir -p /etc/nexus-data/etc/jetty
+      # -- we first need to copy the default Jetty config to the persistent volume so it isn't overwritten on restart
+      docker exec -u root nexus cp /opt/sonatype/nexus/etc/jetty/jetty-https.xml /nexus-data/etc/jetty/
+      # -- then we replace password values with the ssl cert keystore password
+      xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='KeyStorePassword']" \
+        -v "$CERT_PASSWORD" /etc/nexus-data/etc/jetty/jetty-https.xml
+      xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='KeyManagerPassword']" \
+        -v "$CERT_PASSWORD" /etc/nexus-data/etc/jetty/jetty-https.xml
+      xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='TrustStorePassword']" \
+        -v "$CERT_PASSWORD" /etc/nexus-data/etc/jetty/jetty-https.xml
+      # -- then update the location of our keystore
+      xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='KeyStorePath']" \
+        -v /nexus-data/keystores/keystore.jks /etc/nexus-data/etc/jetty/jetty-https.xml
+      xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='TrustStorePath']" \
+        -v /nexus-data/keystores/keystore.jks /etc/nexus-data/etc/jetty/jetty-https.xml
+
+      # Add jetty configuration and ssl port to Nexus properties
+      cat >> /etc/nexus-data/etc/nexus.properties <<'EOF'
       application-port-ssl=8443
       nexus-args=$${jetty.etc}/jetty.xml,$${jetty.etc}/jetty-http.xml,$${jetty.etc}/jetty-requestlog.xml,/nexus-data/etc/jetty/jetty-https.xml
-    permissions: '0755'
+      EOF
+
+      # Restart the container for changes to take effect
+      docker restart nexus
+      echo 'Nexus ssl configuration completed.'
+    permissions: '0744'
+
   # Write a script that will reset the admin password for Nexus to the one TF generated
   - path: /home/adminuser/reset-nexus-password.sh
     content: |
       #!/bin/bash
       # Get the current password so we can post to the API
       # (this is created in the /nexus-data mounted volume as part of Nexus container start-up in cloud-init)
-      password_timeout=120
+      password_timeout=300
       echo 'Checking for Nexus admin password file...'
       while [ ! -f /etc/nexus-data/admin.password ]; do
         # We must first wait for the file to be created
@@ -75,18 +133,18 @@ write_files:
       CURRENT_PASSWORD=$(cat /etc/nexus-data/admin.password)
 
       # Set our own admin password so we can connect to the Nexus repository manager later on using TF KV secret
-      reset_timeout=120
-      echo 'Nexus default admin password found. Resetting...'
+      reset_timeout=300
+      echo "Nexus default admin password found ($CURRENT_PASSWORD). Resetting..."
       # While the container is starting up it may return a number of transient errors (i.e. connection reset) which we need to retry until operational
       # NOTE: we can't use curl's built-in retry flags as it doesn't catch for the connection reset response
       res=1
       while test "$res" != "0"; do
         curl -ifu admin:$CURRENT_PASSWORD -XPUT -H 'Content-Type:text/plain' --data '${nexus_admin_password}' \
           http://localhost/service/rest/v1/security/users/admin/change-password
-        $res=$?
+        res=$?
         echo "Attempt to reset password finished with code $res"
         if test "$res" == "0"; then
-          echo 'Password reset successfully. Admin can now log in with secret stored in KeyVault. Nexus configuration complete.'
+          echo 'Password reset successfully. Admin can now log in with secret stored in KeyVault.'
         else
           if [ $reset_timeout == 0 ]; then
             echo 'ERROR - Timeout while trying to reset Nexus admin password'
@@ -100,19 +158,9 @@ write_files:
 
 runcmd:
   - export DEBIAN_FRONTEND=noninteractive
-  # Give the Nexus process write permissions on the folder mounted as persistent volume
+    # Give the Nexus process write permissions on the folder mounted as persistent volume
   - chown -R 200 /etc/nexus-data
-  # Prepare ssl certificate
-  - az login --identity -u ${msi_id}
-  # -- get cert from kv as secret so it contains private key
-  - az keyvault secret download --vault-name ${vault_name} --name ${ssl_cert_name} --file temp.pfx --encoding base64
-  # -- az cli strips out password from cert which we need to re-add for jks by converting to PEM then back to PFX with pwd
-  - openssl pkcs12 -in temp.pfx -out temp.pem -nodes -password 'pass:'
-  - openssl pkcs12 -export -out nexus-ssl.pfx -in temp.pem -password "pass:${ssl_cert_password}"
-  # -- import into jks within nexus volume
-  - keytool -v -importkeystore -srckeystore nexus-ssl.pfx -srcstoretype PKCS12 -destkeystore /etc/nexus-data/keystores/keystore.jks
-      -deststoretype JKS -srcstorepass "${ssl_cert_password}" -deststorepass "${ssl_cert_password}"
-  # Run the nexus container (mapping volume for nexus config)
+    # Run the nexus container with mapped volume for nexus config
   - docker run -d
       -p 80:8081 -p 443:8443
       -v /etc/nexus-data:/nexus-data
@@ -120,17 +168,5 @@ runcmd:
       --name nexus
       --log-driver local
       sonatype/nexus3
-  # Configure Jetty instance within Nexus to consume ssl cert
-  - mkdir /etc/nexus-data/etc/jetty
-  # -- we first need to copy the default Jetty config to the persistent volume so it isn't overwritten on restart
-  - docker exec -u root nexus cp /opt/sonatype/nexus/etc/jetty/jetty-https.xml /nexus-data/etc/jetty/
-  # -- then we replace password values with the ssl cert keystore password
-  - xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='KeyStorePassword']" -v "${ssl_cert_password}" jetty-https.xml
-  - xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='KeyManagerPassword']" -v "${ssl_cert_password}" jetty-https.xml
-  - xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='TrustStorePassword']" -v "${ssl_cert_password}" jetty-https.xml
-  # -- update the location of our keystore
-  - xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='KeyStorePath']" -v /nexus-data/keystores/keystore.jks jetty-https.xml
-  - xmlstarlet ed -P --inplace -u "/Configure[@id='Server']/New[@id='sslContextFactory']/Set[@name='TrustStorePath']" -v /nexus-data/keystores/keystore.jks jetty-https.xml
-  - docker restart nexus
-  # Run the script to reset Nexus password (we write this as a script file first to avoid tricky handling of special chars in yml)
   - bash /home/adminuser/reset-nexus-password.sh
+  - bash /home/adminuser/configure-nexus-ssl.sh
