Make Java fail

diff --git a/.github/workflows/build_docker_images.yml b/.github/workflows/build_docker_images.yml
--- a/.github/workflows/build_docker_images.yml
+++ b/.github/workflows/build_docker_images.yml
@@ -44,9 +44,9 @@ jobs:
         uses: docker/setup-buildx-action@v1
 
       # Unit Tests are executed by calling the 'test-results' target in the
-      # docker file. If the pytest finds any errors, it will exit 1 and the
-      # build will stop. The test results are only published if we have a
-      # successful run.
+      # Dockerfile's. Test runner exit codes must be swallowed (and kept) so we
+      # can output the test results. This means we have to check for failure
+      # trigger files in later steps.
       - name: "Test image: api"
         # test should be before build since its docker target
         # is prior to runtime
@@ -66,9 +66,9 @@ jobs:
         id: check_api_test_result
         uses: andstor/file-existence-action@v1
         with:
-          files: "test-results/pytest_unit_failed"
+          files: "test-results/pytest_api_unit_failed"
 
-      - name: PyTest failure
+      - name: API app unit test failure
         if: steps.check_api_test_result.outputs.files_exists == 'true'
         run: exit 1
 
@@ -106,6 +106,16 @@ jobs:
           target: test-results
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+      - name: "Check maven failure file existence"
+        id: check_maven_test_result
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "test-results/guacamole_package_failed"
+
+      - name: Guacamole Unit Tests failed
+        if: steps.check_maven_test_result.outputs.files_exists == 'true'
+        run: exit 1
 
       - name: "Build image: guacamole_server"
         if: |
