Add support for allowed subnet ID in Key Vault network access configuration Add ALLOWED_SUBNET_ID input to workflows and scripts for VNet exception handling

diff --git a/.github/workflows/deploy_tre_reusable.yml b/.github/workflows/deploy_tre_reusable.yml
--- a/.github/workflows/deploy_tre_reusable.yml
+++ b/.github/workflows/deploy_tre_reusable.yml
@@ -1,7 +1,7 @@
 ---
 name: Deploy Azure TRE Reusable
 
-on:  # yamllint disable-line rule:truthy
+on: # yamllint disable-line rule:truthy
   workflow_call:
     inputs:
       prRef:
@@ -96,6 +96,9 @@ on:  # yamllint disable-line rule:truthy
       EXTERNAL_KEY_STORE_ID:
         description: ""
         required: false
+      ALLOWED_SUBNET_ID:
+        description: Enables vnet exception for the subnet to access private resources
+        required: true
 
 # This will prevent multiple runs of this entire workflow.
 # We should NOT cancel in progress runs as that can destabilize the environment.
@@ -180,6 +183,10 @@ jobs:
             echo "Missing variable: LOCATION" && exit 1
           fi
 
+          if [ "${{ secrets.ALLOWED_SUBNET_ID }}" == '' ]; then
+            echo "Missing variable: ALLOWED_SUBNET_ID" && exit 1
+          fi
+
       - name: Report check status start
         if: inputs.prHeadSha != ''
         uses: LouisBrunner/checks-action@v2.0.0
@@ -255,6 +262,7 @@ jobs:
           ENABLE_CMK_ENCRYPTION: ${{ vars.ENABLE_CMK_ENCRYPTION }}
           ENCRYPTION_KV_NAME: ${{ secrets.ENCRYPTION_KV_NAME }}
           EXTERNAL_KEY_STORE_ID: ${{ secrets.EXTERNAL_KEY_STORE_ID }}
+          ALLOWED_SUBNET_ID: ${{ secrets.ALLOWED_SUBNET_ID }}
 
       - name: ACR Login
         # failure in the first attempt indicates a new ACR, so we need to try again after it's been created
@@ -279,7 +287,12 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        target: [build-and-push-api, build-and-push-resource-processor, build-and-push-airlock-processor]
+        target:
+          [
+            build-and-push-api,
+            build-and-push-resource-processor,
+            build-and-push-airlock-processor,
+          ]
 
     steps:
       - name: Checkout
@@ -371,6 +384,7 @@ jobs:
           ENABLE_CMK_ENCRYPTION: ${{ vars.ENABLE_CMK_ENCRYPTION }}
           ENCRYPTION_KV_NAME: ${{ secrets.ENCRYPTION_KV_NAME }}
           EXTERNAL_KEY_STORE_ID: ${{ secrets.EXTERNAL_KEY_STORE_ID }}
+          ALLOWED_SUBNET_ID: ${{ secrets.ALLOWED_SUBNET_ID }}
 
       - name: API Healthcheck
         uses: ./.github/actions/devcontainer_run_command
@@ -390,38 +404,70 @@ jobs:
     strategy:
       matrix:
         include:
-          - {BUNDLE_TYPE: "workspace",
-             BUNDLE_DIR: "./templates/workspaces/base"}
-          - {BUNDLE_TYPE: "workspace",
-             BUNDLE_DIR: "./templates/workspaces/unrestricted"}
-          - {BUNDLE_TYPE: "workspace",
-             BUNDLE_DIR: "./templates/workspaces/airlock-import-review"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/azureml"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/gitea"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/mysql"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/health-services"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/databricks"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/ohdsi"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/azuresql"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/openai"}
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm"}
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm"}
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-export-reviewvm"}
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-import-reviewvm"}
+          - {
+              BUNDLE_TYPE: "workspace",
+              BUNDLE_DIR: "./templates/workspaces/base",
+            }
+          - {
+              BUNDLE_TYPE: "workspace",
+              BUNDLE_DIR: "./templates/workspaces/unrestricted",
+            }
+          - {
+              BUNDLE_TYPE: "workspace",
+              BUNDLE_DIR: "./templates/workspaces/airlock-import-review",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/azureml",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/gitea",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/mysql",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/health-services",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/databricks",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/ohdsi",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/azuresql",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/openai",
+            }
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm",
+            }
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm",
+            }
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-export-reviewvm",
+            }
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-import-reviewvm",
+            }
     environment: ${{ inputs.environmentName }}
     steps:
       - name: Checkout
@@ -457,22 +503,38 @@ jobs:
     strategy:
       matrix:
         include:
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/firewall/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/gitea/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/admin-vm/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/airlock_notifier/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/certs/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/cyclecloud/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/sonatype-nexus-vm/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/databricks-auth/"}
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/firewall/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/gitea/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/admin-vm/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/airlock_notifier/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/certs/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/cyclecloud/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/sonatype-nexus-vm/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/databricks-auth/",
+            }
     environment: ${{ inputs.environmentName }}
     steps:
       - name: Checkout
@@ -508,22 +570,38 @@ jobs:
     strategy:
       matrix:
         include:
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/firewall"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/gitea"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/admin-vm/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/airlock_notifier/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/certs/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/cyclecloud/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/sonatype-nexus-vm/"}
-          - {BUNDLE_TYPE: "shared_service",
-             BUNDLE_DIR: "./templates/shared_services/databricks-auth/"}
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/firewall",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/gitea",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/admin-vm/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/airlock_notifier/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/certs/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/cyclecloud/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/sonatype-nexus-vm/",
+            }
+          - {
+              BUNDLE_TYPE: "shared_service",
+              BUNDLE_DIR: "./templates/shared_services/databricks-auth/",
+            }
     environment: ${{ inputs.environmentName }}
     steps:
       - name: Checkout
@@ -566,28 +644,50 @@ jobs:
       matrix:
         include:
           # bundles type can be inferred from the bundle dir (but this is more explicit)
-          - {BUNDLE_TYPE: "workspace",
-             BUNDLE_DIR: "./templates/workspaces/base"}
-          - {BUNDLE_TYPE: "workspace",
-             BUNDLE_DIR: "./templates/workspaces/unrestricted"}
-          - {BUNDLE_TYPE: "workspace",
-             BUNDLE_DIR: "./templates/workspaces/airlock-import-review"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/azureml"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/gitea"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/mysql"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/health-services"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/databricks"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/ohdsi"}
-          - {BUNDLE_TYPE: "workspace_service",
-             BUNDLE_DIR: "./templates/workspace_services/azuresql"}
+          - {
+              BUNDLE_TYPE: "workspace",
+              BUNDLE_DIR: "./templates/workspaces/base",
+            }
+          - {
+              BUNDLE_TYPE: "workspace",
+              BUNDLE_DIR: "./templates/workspaces/unrestricted",
+            }
+          - {
+              BUNDLE_TYPE: "workspace",
+              BUNDLE_DIR: "./templates/workspaces/airlock-import-review",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/azureml",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/gitea",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/mysql",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/health-services",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/databricks",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/ohdsi",
+            }
+          - {
+              BUNDLE_TYPE: "workspace_service",
+              BUNDLE_DIR: "./templates/workspace_services/azuresql",
+            }
 
     environment: ${{ inputs.environmentName }}
     steps:
@@ -631,18 +731,26 @@ jobs:
     strategy:
       matrix:
         include:
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm",
-             WORKSPACE_SERVICE_NAME: "tre-service-guacamole"}
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm",
-             WORKSPACE_SERVICE_NAME: "tre-service-guacamole"}
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-export-reviewvm",
-             WORKSPACE_SERVICE_NAME: "tre-service-guacamole"}
-          - {BUNDLE_TYPE: "user_resource",
-             BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-import-reviewvm",
-             WORKSPACE_SERVICE_NAME: "tre-service-guacamole"}
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm",
+              WORKSPACE_SERVICE_NAME: "tre-service-guacamole",
+            }
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm",
+              WORKSPACE_SERVICE_NAME: "tre-service-guacamole",
+            }
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-export-reviewvm",
+              WORKSPACE_SERVICE_NAME: "tre-service-guacamole",
+            }
+          - {
+              BUNDLE_TYPE: "user_resource",
+              BUNDLE_DIR: "./templates/workspace_services/guacamole/user_resources/guacamole-azure-import-reviewvm",
+              WORKSPACE_SERVICE_NAME: "tre-service-guacamole",
+            }
     environment: ${{ inputs.environmentName }}
     steps:
       - name: Checkout
@@ -805,7 +913,8 @@ jobs:
     if: ${{ inputs.e2eTestsCustomSelector != '' }}
     runs-on: ubuntu-latest
     environment: ${{ inputs.environmentName }}
-    needs: [deploy_shared_services, register_bundles, register_user_resource_bundles]
+    needs:
+      [deploy_shared_services, register_bundles, register_user_resource_bundles]
     timeout-minutes: 300
     steps:
       - name: Checkout
