remove check

diff --git a/.github/workflows/register_tre_bundle.yml b/.github/workflows/register_tre_bundle.yml
--- a/.github/workflows/register_tre_bundle.yml
+++ b/.github/workflows/register_tre_bundle.yml
@@ -44,58 +44,58 @@ jobs:
           echo "ciGitRef    : ${{ github.ref }}"
           echo "environment : ${{ inputs.environmentName }}"
 
-      - name: Check required values
-        id: check_required_values
-        # since this is a resuable workflow, required=true secrets will always have a value but it can be empty.
-        run: |
-          if [ "${{ secrets.AAD_TENANT_ID }}" == '' ]; then
-            echo "Missing secret: AAD_TENANT_ID" && exit 1
-          fi
-          if [ "${{ secrets.ACR_NAME }}" == '' ]; then
-            echo "Missing secret: ACR_NAME" && exit 1
-          fi
-          if [ "${{ secrets.API_CLIENT_ID }}" == '' ]; then
-            echo "Missing secret: API_CLIENT_ID" && exit 1
-          fi
-          if [ "${{ secrets.API_CLIENT_SECRET }}" == '' ]; then
-            echo "Missing secret: API_CLIENT_SECRET" && exit 1
-          fi
-          if [ "${{ secrets.APPLICATION_ADMIN_CLIENT_ID }}" == '' ]; then
-            echo "Missing secret: APPLICATION_ADMIN_CLIENT_ID" && exit 1
-          fi
-          if [ "${{ secrets.APPLICATION_ADMIN_CLIENT_SECRET }}" == '' ]; then
-            echo "Missing secret: APPLICATION_ADMIN_CLIENT_SECRET" && exit 1
-          fi
-          if [ "${{ secrets.MGMT_RESOURCE_GROUP_NAME }}" == '' ]; then
-            echo "Missing secret: MGMT_RESOURCE_GROUP_NAME" && exit 1
-          fi
-          if [ "${{ secrets.MGMT_STORAGE_ACCOUNT_NAME }}" == '' ]; then
-            echo "Missing secret: MGMT_STORAGE_ACCOUNT_NAME" && exit 1
-          fi
-          if [ "${{ secrets.SWAGGER_UI_CLIENT_ID }}" == '' ]; then
-            echo "Missing secret: SWAGGER_UI_CLIENT_ID" && exit 1
-          fi
-          if [ "${{ secrets.TEST_APP_ID }}" == '' ]; then
-            echo "Missing secret: TEST_APP_ID" && exit 1
-          fi
-          if [ "${{ secrets.TEST_WORKSPACE_APP_ID }}" == '' ]; then
-            echo "Missing secret: TEST_WORKSPACE_APP_ID" && exit 1
-          fi
-          if [ "${{ secrets.TEST_WORKSPACE_APP_SECRET }}" == '' ]; then
-            echo "Missing secret: TEST_WORKSPACE_APP_SECRET" && exit 1
-          fi
-          if [ "${{ secrets.TEST_ACCOUNT_CLIENT_ID }}" == '' ]; then
-            echo "Missing secret: TEST_ACCOUNT_CLIENT_ID" && exit 1
-          fi
-          if [ "${{ secrets.TEST_ACCOUNT_CLIENT_SECRET }}" == '' ]; then
-            echo "Missing secret: TEST_ACCOUNT_CLIENT_SECRET" && exit 1
-          fi
-          if [ "${{ secrets.TRE_ID }}" == '' ]; then
-            echo "Missing secret: TRE_ID" && exit 1
-          fi
-          if [ "${{ secrets.AZURE_CREDENTIALS }}" == '' ]; then
-            echo "Missing secret: AZURE_CREDENTIALS" && exit 1
-          fi
+      # - name: Check required values
+      #   id: check_required_values
+      #   # since this is a resuable workflow, required=true secrets will always have a value but it can be empty.
+      #   run: |
+      #     if [ "${{ secrets.AAD_TENANT_ID }}" == '' ]; then
+      #       echo "Missing secret: AAD_TENANT_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.ACR_NAME }}" == '' ]; then
+      #       echo "Missing secret: ACR_NAME" && exit 1
+      #     fi
+      #     if [ "${{ secrets.API_CLIENT_ID }}" == '' ]; then
+      #       echo "Missing secret: API_CLIENT_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.API_CLIENT_SECRET }}" == '' ]; then
+      #       echo "Missing secret: API_CLIENT_SECRET" && exit 1
+      #     fi
+      #     if [ "${{ secrets.APPLICATION_ADMIN_CLIENT_ID }}" == '' ]; then
+      #       echo "Missing secret: APPLICATION_ADMIN_CLIENT_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.APPLICATION_ADMIN_CLIENT_SECRET }}" == '' ]; then
+      #       echo "Missing secret: APPLICATION_ADMIN_CLIENT_SECRET" && exit 1
+      #     fi
+      #     if [ "${{ secrets.MGMT_RESOURCE_GROUP_NAME }}" == '' ]; then
+      #       echo "Missing secret: MGMT_RESOURCE_GROUP_NAME" && exit 1
+      #     fi
+      #     if [ "${{ secrets.MGMT_STORAGE_ACCOUNT_NAME }}" == '' ]; then
+      #       echo "Missing secret: MGMT_STORAGE_ACCOUNT_NAME" && exit 1
+      #     fi
+      #     if [ "${{ secrets.SWAGGER_UI_CLIENT_ID }}" == '' ]; then
+      #       echo "Missing secret: SWAGGER_UI_CLIENT_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.TEST_APP_ID }}" == '' ]; then
+      #       echo "Missing secret: TEST_APP_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.TEST_WORKSPACE_APP_ID }}" == '' ]; then
+      #       echo "Missing secret: TEST_WORKSPACE_APP_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.TEST_WORKSPACE_APP_SECRET }}" == '' ]; then
+      #       echo "Missing secret: TEST_WORKSPACE_APP_SECRET" && exit 1
+      #     fi
+      #     if [ "${{ secrets.TEST_ACCOUNT_CLIENT_ID }}" == '' ]; then
+      #       echo "Missing secret: TEST_ACCOUNT_CLIENT_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.TEST_ACCOUNT_CLIENT_SECRET }}" == '' ]; then
+      #       echo "Missing secret: TEST_ACCOUNT_CLIENT_SECRET" && exit 1
+      #     fi
+      #     if [ "${{ secrets.TRE_ID }}" == '' ]; then
+      #       echo "Missing secret: TRE_ID" && exit 1
+      #     fi
+      #     if [ "${{ secrets.AZURE_CREDENTIALS }}" == '' ]; then
+      #       echo "Missing secret: AZURE_CREDENTIALS" && exit 1
+      #     fi
 
       - name: Report check status start
         if: github.sha != ''
