Add failure file check

diff --git a/.github/workflows/test_results.yml b/.github/workflows/test_results.yml
--- a/.github/workflows/test_results.yml
+++ b/.github/workflows/test_results.yml
@@ -49,3 +49,12 @@ jobs:
           event_file: artifacts/Event File/event.json
           event_name: ${{ github.event.workflow_run.event }}
           files: "artifacts/**/*.xml"
+
+      # The following step is the catch situations where the tests didn't run at all.
+      - name: Check failure files
+        run: |
+          if compgen -G "artifacts/**/pytest*failed" > /dev/null; then
+            echo "Tests failure file(s) exist. Some tests have failed or didn't run at all! \
+              Check the artifacts for details."
+            exit 1
+          fi
