rename

diff --git a/.github/workflows/ui_test_results.yml b/.github/workflows/ui_test_results.yml
--- a/.github/workflows/ui_test_results.yml
+++ b/.github/workflows/ui_test_results.yml
@@ -1,6 +1,6 @@
 ---
 # This workflow is required to publish test results from forks
-name: Test Results
+name: UI Test Results
 
 on: # yamllint disable-line rule:truthy
   workflow_run:
@@ -13,7 +13,7 @@ on: # yamllint disable-line rule:truthy
 
 jobs:
   test-results:
-    name: Test Results
+    name: UI Test Results
     runs-on: ubuntu-latest
     if: github.event.workflow_run.conclusion != 'skipped'
 
@@ -52,14 +52,14 @@ jobs:
           check_name: "Unit Test Results"
           comment_mode: always
 
-      # The following step is the catch situations where the tests didn't run at all.
-      - name: Check failure files
-        run: |
-          if compgen -G "artifacts/**/pytest*failed" > /dev/null; then
-            echo "Tests failure file(s) exist. Some tests have failed or didn't run at all! \
-              Check the artifacts for details."
-            exit 1
-          fi
+      # # The following step is the catch situations where the tests didn't run at all.
+      # - name: Check failure files
+      #   run: |
+      #     if compgen -G "artifacts/**/pytest*failed" > /dev/null; then
+      #       echo "Tests failure file(s) exist. Some tests have failed or didn't run at all! \
+      #         Check the artifacts for details."
+      #       exit 1
+      #     fi
 
       # For PR builds triggered from comment builds, the GITHUB_REF is set to main
       # so the checks aren't automatically associated with the PR
